### YamlMime:YamlDocument
ms.openlocfilehash: d6c91dd84a0ae0bfa5ffccff2f8961f95ad4dda8
ms.sourcegitcommit: d4c076beea3a8d9e09c9d2f4a63428dc72dd9806
ms.translationtype: HT
ms.contentlocale: hu-HU
ms.lasthandoff: 08/01/2018
ms.locfileid: "39399246"
documentType: LandingData
title: Ansible az Azure-ban – Dokumentáció
metadata:
  title: Ansible az Azure-ban – Dokumentáció – Oktatóanyagok, minták, referenciák és forrásanyagok
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/16/2018
  ms.author: tarcher
abstract:
  description: Az <a href="http://www.ansible.com">Ansible</a> használatával automatizálható a felhőalapú üzembe helyezés, a konfigurációkezelés és az alkalmazások üzembe helyezése.
sections:
- title: 5 perces gyors útmutatók
  items:
  - type: paragraph
    text: Az Ansible konfigurálása és felhasználása Linux rendszerű virtuális gépek Azure-ban való létrehozására.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Az Ansible konfigurálása
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Linux rendszerű virtuális gép létrehozása
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Részletes útmutatók
  items:
  - type: paragraph
    text: Megtudhatja, hogyan hozhat létre és felügyelhet Azure számítási, hálózatkezelési és tárolási infrastruktúrákat az Ansible használatával.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Linux rendszerű virtuális gép létrehozása, beleértve a virtuális hálózatot, a nyilvános IP-címet és a virtuális hálózati kártyát is.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Csatlakozás Azure-beli virtuális gépekhez, és Ansible-forgatókönyvek futtatása a Cloud Shellben.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Az Azure-erőforrások dinamikus leltárának létrehozása és kezelése.</a>
    - html: <a href="./ansible-create-configure-vmss">Virtuálisgép-méretezési csoportok létrehozása és kezelése az Azure-ban.</a>
    - html: <a href="./ansible-deploy-app-vmss">Alkalmazások üzembe helyezése virtuálisgép-méretezési csoportokban az Azure-ban.</a>
    - html: <a href="./ansible-create-configure-aks">Azure Kubernetes Service fürtök létrehozása és kezelése.</a>
- title: Referencia
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Forgatókönyv-szerepkörök
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Kiadások és szolgáltatások
      html: <p><a href="./ansible-matrix.md">A modulok és szerepkörök szolgáltatásmátrixa</a></p>
    - title: Eszközök
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code-bővítmény az Ansible-höz</a></p>
